### ISSUE TITLE
Develop plan to test legal disclaimer

### ISSUE THREAD

**Issue by acolter** [18F/clinical-trials#32]

**Comment by nicoleslaw** [comment]
My first question is: are they open to suggestions from an editor? I've included some edits here, including removing typos and redundant info on the longform disclaimer: https://docs.google.com/document/d/1XIxMtuZggPeEbfpFdfuTwbz8fQlm7xVDhkF8Wl1jb70/edit#

### Ideas for the test plan

1. Test this as part of a broader usability inquiry with Invision or a paper prototype if in person.
1. Ask the reader what this site is about, what kinds of information they're looking for in general.
1. Draw their attention to the disclaimer where it would be (in context of the design).
1. Ask questions to understand their expectations and interpretations.
1. Ask them to click through to the full disclaimer, read it slowly, and repeat similar questions from the short version.

Alternatively, we could try a one-sentence link instead of the short version, but I would defer to the product owner and legal team on that idea.

### Sample conversation guide

#### 1. ClinicalTrials.gov

Take a look around this page.

  - What can you do from here? What’s this site for?
  - Do you see anything else on this page that interests you? What do you notice?
  - What do you like or dislike?
  - After looking at this page, do you have any questions?

#### 2. Let’s look at the paragraph at the top of the page. Go ahead and read through it slowly. 

- Do you have any questions about it?
- How do you interpret that?
- Is there any other information that you’re looking for?
- Looking at the second paragraph—do you have questions about where the information on this site comes from?

#### 3. Now, let's click through to the full disclaimer. Again, take some time to read it slowly.

- Do you have any questions about it?
- Is there any other information that would help you here?

**Comment by acolter** [comment]
Closing all issues from Phase 1
