### ISSUE TITLE
Wireframe approaches to test

### ISSUE THREAD

**Issue by acolter** [18F/clinical-trials#37]

**Comment by austinhernandez** [comment]
Decided on strategy for working session that will include a design studio. I will design some wireframes using USWDS to "test the waters" with the CT.gov team. @juliaelman will be dedicating a few hours to give design feedback/review on a page.

I am prototyping some solutions based on observations we noticed in the first round of interview testing. Our observations are noted in [this Mural board](https://app.mural.ly/t/gsa6/m/gsa6/1489157912721):
- Search elasticity
- Search result prioritization
- Home page content that is missing
- Homepage content in plain language
- Summary page content organization

**Comment by austinhernandez** [comment]
clickable prototype here: https://invis.io/R9AVPDEU2#/223853798_Homepage

Questions for client regarding mocks:

Content questions from @nicoleslaw [Google Doc with text edits](https://docs.google.com/document/d/1aUEyNXF_R61I0TlmrcyqWY_FSZj9f2SjUxC-i44wd-8/edit#  )
- I noticed that the site often uses `study` and `trial` interchangeably. Is there a difference to our stakeholders? Based on the glossary, it seems like `trials` are only one kind of `study` on the site, but maybe I am splitting hairs:
>CLINICAL STUDY
A research study using human subjects to evaluate biomedical or health-related outcomes. Two types of clinical studies are Interventional studies (or clinical trials) and Observational studies.
>INTERVENTIONAL STUDY (or Clinical Trial)
A clinical study in which participants are assigned to receive one or more interventions (or no intervention) so that researchers can evaluate the effects of the interventions on biomedical or health-related outcomes. The assignments are determined by the study protocol. Participants may receive diagnostic, therapeutic, or other types of interventions. A Study Type.
>OBSERVATIONAL STUDY
A clinical study in which participants identified as belonging to study groups are assessed for biomedical or health outcomes. Participants may receive diagnostic, therapeutic, or other types of interventions, but the investigator does not assign participants to specific interventions (as in an Interventional study). A Study Type.

- What does "accepts healthy volunteers" mean?
  - ACCEPTS HEALTHY VOLUNTEERS: Indicates whether a clinical study allows people who do not have the condition or related conditions or symptoms being studied to participate in that study. (See also Accepts Healthy Volunteers data element on ClinicalTrials.gov.)

## To learn from CT team:
- Technical restrictions
- What worked / didn't in the past?
  - splitting content/user groups (e.g. I am a scientist or I am a patient) 
- Is plain language doable?
  - Does the QA title format work?
- What does the document that the researcher/doctor/scientist have to upload look like?

##Home:
- Learn more about the DB to do more elastic search queries?
- Feedback has been that w/ too many input fields it looks like they are all required
- Make sure we let users know that the results / database shows info from past and previous trials

## Search results page:
- What is rank number? (How is that determined)
- Are there ways to categorize the interventions so they are sortable/filterable?

## Study record detail page:
- Used content from [this study on PTSD and mobile phones]( https://clinicaltrials.gov/beta/show/NCT02780635?cond=PTSD&cntry1=NA%3AUS&state1=NA%3AUS%3ACA&draw=1&rank=2)
- Took out a lot of inline links to keep users from thinking they missed something on the page.
- Punctuation slows people down on bullets
- *V2 concept/idea (thanks @esgoodman )*
  - Top/hero section as a quick "Are you eligible or not?" before you get into the nitty gritty of the site. For example: Putting eligibility information on top like "Are you a veteran suffering with PTSD? If so, you may be eligible - scroll down to read more details."

**Comment by acolter** [comment]
Closing all issues from Phase 1
